### ISSUE TITLE
Install and upgrade problem

### ISSUE THREAD

**Issue by krisztianlukacs** [avi-perl/rich_tools#3]
Hi Avi,

I wanted to update the package but I got this error message:

# 1.
sudo pip3 install rich-tools --upgrade
Collecting rich-tools
  Could not find a version that satisfies the requirement rich-tools (from versions: )
No matching distribution found for rich-tools

# 2.
sudo pip3 install "git+https://github.com/avi-perl/rich_tools"
Collecting git+https://github.com/avi-perl/rich_tools
  Cloning https://github.com/avi-perl/rich_tools to /tmp/pip-req-build-kbs7wded
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-kbs7wded/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-kbs7wded/

**Comment by UltraStudioLTD** [comment]
@krisztianlukacs Problem is that there is no "setup.py" in this repository and installation is done using [**pyproject.toml**](https://github.com/avi-perl/rich_tools/blob/master/pyproject.toml) so here is what you need to do:

1. Clone repository using `git clone https://github.com/avi-perl/rich_tools`
2. `cd rich_tools`
3. Install dependencies using `pip install --user -r requirements.txt` if you want to install it for the only current user. Remove `--user` if you want to install it globally (make require `root` or `admin` privileges).
4. Install module using `pip install --user .` or remove `--user` if similar to **3**rd step
5. Done. If you encountered any errors ask away
